export default {
  '01d': ':sunny:',
  '01n': ':sunny:',
  '02d': ':sun_behind_cloud:',
  '02n': ':sun_behind_cloud:',
  '03d': ':cloud:',
  '03n': ':cloud:',
  '04d': ':left_speech_bubble:',
  '04n': ':left_speech_bubble:',
  '09d': ':rain_cloud:',
  '09n': ':rain_cloud:',
  '10d': ':partly_sunny_rain:',
  '10n': ':partly_sunny_rain:',
  '11d': ':thunder_cloud_and_rain:',
  '11n': ':thunder_cloud_and_rain:',
  '13d': ':snow_cloud:',
  '13n': ':snow_cloud:',
  '50d': ':fog:',
  '50n': ':fog:',
}
