export default {
  1: ':sunny:', //'selkeää'
  2: ':partly_sunny:', //'puolipilvistä'
  21: ':droplet:', //'heikkoja sadekuuroja'
  22: ':white_sun_rain_cloud:', //'sadekuuroja'
  23: ':shower:', //'voimakkaita sadekuuroja'
  3: ':cloud:', //'pilvistä'
  31: ':droplet:', //'heikkoa vesisadetta'
  32: ':sweat_drops:', //'vesisadetta'
  33: ':shower:', //'voimakasta vesisadetta'
  41: ':snowflake:', //'heikkoja lumikuuroja'
  42: ':cloud_snow:', //'lumikuuroja'
  43: ':snowman2:', //'voimakkaita lumikuuroja'
  51: ':snowflake:', //'heikkoa lumisadetta'
  52: ':cloud_snow:', //'lumisadetta'
  53: ':snowman2:', //'voimakasta lumisadetta'
  61: ':thunder_cloud_rain:', //'ukkoskuuroja'
  62: ':thunder_cloud_rain:', //'voimakkaita ukkoskuuroja'
  63: ':thunder_cloud_rain:', //'ukkosta'
  64: ':thunder_cloud_rain:', //'voimakasta ukkosta'
  71: ':droplet:', //'heikkoja räntäkuuroja'
  72: ':white_sun_rain_cloud:', //'räntäkuuroja'
  73: ':shower:', //'voimakkaita räntäkuuroja'
  81: ':droplet:', //'heikkoa räntäsadetta'
  82: ':sweat_drops:', //'räntäsadetta'
  83: ':shower:', //'voimakasta räntäsadetta'
  91: ':fog:', //'utua'
  92: ':fog:',//'sumua'
}