export default {
  '01d': ':sunny:',
  '01n': ':sunny:',
  '02d': ':partly_sunny:',
  '02n': ':partly_sunny:',
  '03d': ':cloud:',
  '03n': ':cloud:',
  '04d': ':cloud:',
  '04n': ':cloud:',
  '09d': ':cloud_rain:',
  '09n': ':cloud_rain:',
  '10d': ':white_sun_rain_cloud:',
  '10n': ':white_sun_rain_cloud:',
  '11d': ':cloud_lightning:',
  '11n': ':cloud_lightning:',
  '13d': ':cloud_snow:',
  '13n': ':cloud_snow:',
  '50d': ':fog:',
  '50n': ':fog:',
}
